import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import PageTransition from "./components/PageTransition";
import { checkEnvironmentVariables, warnOptionalEnvironmentVariables } from "@/lib/env-check";

// 在构建时检查环境变量
if (process.env.NODE_ENV === 'production') {
  checkEnvironmentVariables();
  warnOptionalEnvironmentVariables();
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <PageTransition>
            {children}
          </PageTransition>
        </Providers>
      </body>
    </html>
  );
}
